### ISSUE TITLE
how to run the stuff 

### ISSUE THREAD

**Issue by Creeeeger** [LemonHaze420/ps5-pup_decrypt#2]
ok compile worked fine 
binary is there only when i execute it i become that error:

Starting program: /home/greg/Desktop/ps5-pup_decrypt/payload.elf 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ffe170 in ?? ()
(gdb) bt
#0  0x00007ffff7ffe170 in ?? ()
#1  0x00005555555542f9 in main (dlsym=0x7ffff7ffe170) at source/main.c:18

what now how to fix it / what am i doing wrong 

best regs

**Comment by LemonHaze420** [comment]
You don't run it on PC.

**Comment by Creeeeger** [comment]
Okay and how to run it on a PlayStation or do I need to jailbreak it first
